apiVersion: v1
kind: Namespace
metadata:
  name: library
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-api
  namespace: library
  labels:
    app: library-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
        - name: api
          image: ghcr.io/gerardinhoo/library-api-spring-boot:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            - name: JAVA_TOOL_OPTIONS
              value: '-Xms128m -Xmx384m -XX:MaxRAMPercentage=75'
          ports:
            - containerPort: 8080

          startupProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 24

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

          resources:
            requests:
              cpu: '500m'
              memory: '512Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: library-api
  namespace: library
spec:
  type: LoadBalancer
  selector:
    app: library-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
